Cliente/urls.py
# ptclinic/cliente/urls.py
from django.urls import path
from . import views
from .views import cadastro_view, contacto_view

urlpatterns = [
    path('', views.LadingPage, name='cliente_base'),
    path('cliente/agendar', views.Agendamento, name='agendar'),
    path('cadastro/', cadastro_view, name='cadastro'),  # URL de cadastro
    path('contacto/', contacto_view, name='contacto'),  # URL de contato
]

PTCLINIC/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cliente.urls')),
    path('', include('backoffice.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backoffice/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from . import views
from .views import AgendamentoViewSet, gerenciamento_cadastros_view, cadastros_api_view, contactos_api_view, \
    gerenciamento_contactos_view, user_list_api, atualizar_estado_cadastro

app_name = 'backoffice'
router = DefaultRouter()
router.register(r'agendamentos', AgendamentoViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('login/', views.Login, name='login'),  # Login do backoffice
    path('gerir-agendamentos/', TemplateView.as_view(template_name="backoffice/agendamentos/gerirAgendamentos.html"),
         name='gerir-agendamentos'),
    path('backoffice/', views.LadingPage, name='landingPage'),  # Criar novo usuário
    path('home/', views.LadingPage, name='home_backoffice'),
    path('gerir-cadastros/', gerenciamento_cadastros_view, name='gerenciamento_cadastros'),
    path('api/cadastros/', cadastros_api_view, name='cadastros_api'),  # Certifique-se de que esta URL está correta
    path('api/cadastros/<int:id>/atualizar-estado/', atualizar_estado_cadastro, name='atualizar_estado_cadastro'),

    path('api/contactos/', contactos_api_view, name='contactos_api'),
    path('gerir-contactos/', gerenciamento_contactos_view, name='gerenciamento_contactos'),
    path('api/contactos/<int:contacto_id>/validar/', views.validar_contacto_view, name='validar_contacto'),

    path('users/new/', views.user_create, name='user_create'),  # Criar novo usuário
    path('users/<int:user_id>/edit/', views.user_edit, name='user_edit'),
    path('users/<int:user_id>/delete/', views.user_delete, name='user_delete'),
    path('gerir-acessos/', views.Gerir_Acessos, name='Gerir_Acessos'),  # Dashboard do backoffice
    path('api/users/', user_list_api, name='user_list_api'),  # API de listagem de usuários
    # Adicione outras URLs conforme necessário
]

backoffice/models.py
from datetime import time, timedelta, datetime, date

from django.contrib.auth.models import User
from django.db import models
from rest_framework.exceptions import ValidationError

# models.py
from django.db import models

class Cadastro(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField()
    telemovel = models.CharField(max_length=20)
    data_cadastro = models.DateTimeField(auto_now_add=True)
    estado = models.BooleanField(default=False)
    usuario_acao = models.CharField(max_length=100, null=True, blank=True)
    data_acao = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.nome

class Agendamento(models.Model):
    TIPO_CHOICES = [
        ('Consulta', 'Consulta'),
        ('Visita', 'Visita'),
        ('Avaliação Física', 'Avaliação Física'),
    ]

    nome = models.CharField(max_length=100)
    tipo = models.CharField(max_length=50, choices=TIPO_CHOICES)
    data = models.DateField()
    hora = models.TimeField()
    email = models.EmailField()
    contato = models.CharField(max_length=20)
    nota = models.TextField(blank=True, null=True)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.nome} - {self.tipo} em {self.data} às {self.hora}'

    def clean(self):
        # Verificar horário de funcionamento
        if self.data.weekday() == 6:  # Domingo
            raise ValidationError('O ginásio está fechado aos domingos.')

        hora_abertura, hora_fechamento = self.get_horarios_funcionamento()

        if not (hora_abertura <= self.hora <= hora_fechamento):
            raise ValidationError(
                f'Horário de agendamento inválido. O ginásio abre às {hora_abertura} e fecha às {hora_fechamento}.')

        # Verificar sobreposição
        duracao = self.get_duracao()
        hora_fim = (datetime.combine(date.today(), self.hora) + duracao).time()

        agendamentos_conflitantes = Agendamento.objects.filter(
            data=self.data,
            hora__lt=hora_fim,
            hora__gte=self.hora
        ).exclude(pk=self.pk)

        if agendamentos_conflitantes.exists():
            raise ValidationError('Já existe um agendamento neste horário.')

    def get_horarios_funcionamento(self):
        if self.data.weekday() in [0, 1, 2, 3, 4]:  # Segunda a sexta
            return time(7, 0), time(21, 30)
        elif self.data.weekday() == 5:  # Sábado
            return time(9, 0), time(13, 0)
        return None, None

    def get_duracao(self):
        if self.tipo == 'Consulta':
            return timedelta(hours=1)
        elif self.tipo == 'Visita':
            return timedelta(minutes=30)
        elif self.tipo == 'Avaliação Física':
            return timedelta(minutes=45)
        return timedelta(0)

    def save(self, *args, **kwargs):
        self.clean()  # Chamar validação antes de salvar
        super().save(*args, **kwargs)


class Contacto(models.Model):
    nome = models.CharField(max_length=255)
    email = models.EmailField()
    mensagem = models.TextField()
    data_contacto = models.DateTimeField(auto_now_add=True)
    estado = models.BooleanField(default=False)
    validado_por = models.CharField(max_length=255, null=True, blank=True)
    data_acao = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.nome

backoffice/forms.py
# forms.py

from django import forms
from django.contrib.auth.models import User

from backoffice.models import Cadastro
from cliente.models import CadastroImage


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Senha")
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Confirme a senha")

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if self.instance.pk is None and User.objects.filter(username=username).exists():
            raise forms.ValidationError("Nome de usuário já está em uso.")
        return username

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("As senhas não coincidem.")

        return cleaned_data

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']  # Inclua outros campos que você deseja permitir que sejam editados

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        # Customize os campos se necessário
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class CadastroForm(forms.ModelForm):
    class Meta:
        model = Cadastro
        fields = ['nome', 'email', 'telemovel']

backoffice/views.py
import json
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from rest_framework import viewsets, status
from rest_framework.exceptions import ValidationError
from rest_framework.response import Response

from backoffice.forms import UserCreationForm, UserEditForm
from backoffice.models import Agendamento, Cadastro, Contacto
from backoffice.serializers import AgendamentoSerializer
from cliente.models import CadastroImage

def check_is_staff(user):
    return user.is_staff
@login_required
@user_passes_test(check_is_staff)
def LadingPage(request):
    return render(request, 'backoffice/landingPage/landingPage.html')

@login_required
@user_passes_test(check_is_staff)
def gerenciamento_cadastros_view(request):
    return render(request, 'backoffice/cadastro/gerirCadastros.html')

@login_required
@user_passes_test(check_is_staff)
def cadastros_api_view(request):
    cadastros = Cadastro.objects.all().values('id', 'nome', 'email', 'telemovel', 'data_cadastro', 'estado', 'usuario_acao', 'data_acao')
    return JsonResponse(list(cadastros), safe=False)

@csrf_exempt
@login_required
@user_passes_test(check_is_staff)
def atualizar_estado_cadastro(request, id):
    if request.method == 'POST':
        try:
            cadastro = Cadastro.objects.get(id=id)
            data = json.loads(request.body)
            cadastro.estado = data['estado']
            cadastro.usuario_acao = data['usuario_acao']
            cadastro.data_acao = data['data_acao']
            cadastro.save()
            return JsonResponse({'success': True})
        except Cadastro.DoesNotExist:
            return HttpResponseBadRequest('Cadastro não encontrado')
        except Exception as e:
            return HttpResponseBadRequest(f'Erro: {str(e)}')
    else:
        return HttpResponseBadRequest('Método não permitido')

def Login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active and user.is_staff:
                    login(request, user)
                    return redirect(reverse('backoffice:landingPage'))
                else:
                    messages.error(request, 'A conta não tem permissões para acessar essa área.')
            else:
                messages.error(request, 'Nome de usuário ou senha inválidos.')
        else:
            messages.error(request, 'Nome de usuário ou senha inválidos.')
    else:
        form = AuthenticationForm()
    return render(request, 'backoffice/login/login.html', {'form': form})

@login_required
@user_passes_test(check_is_staff)
def user_list_api(request):
    if request.method == 'GET':
        users = User.objects.filter(is_staff=True).values('id', 'username', 'email', 'date_joined')
        users_list = list(users)
        return JsonResponse(users_list, safe=False)

@login_required
@user_passes_test(check_is_staff)
def Gerir_Acessos(request):
    users = User.objects.filter(is_staff=True)  # Filtra apenas usuários que são staff
    return render(request, 'backoffice/admin/gerirAcessos.html', {'users': users})

@login_required
@user_passes_test(check_is_staff)
def user_create(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Novo usuário adicionado com sucesso!')
            return redirect('backoffice:home_backoffice')
    else:
        form = UserCreationForm()
    return render(request, 'backoffice/admin/userCreate.html', {'form': form})

@login_required
@user_passes_test(check_is_staff)
def user_edit(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário atualizado com sucesso!')
            return redirect('backoffice:home_backoffice')
    else:
        form = UserEditForm(instance=user)
    return render(request, 'backoffice/admin/userEdit.html', {'user': user, 'form': form})

@login_required
@user_passes_test(check_is_staff)
def user_delete(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        user.delete()
        messages.success(request, 'Usuário apagado com sucesso!')
        return redirect('backoffice:home_backoffice')
    return render(request, 'backoffice/admin/userDelete.html', {'user': user})

class AgendamentoViewSet(viewsets.ModelViewSet):
    queryset = Agendamento.objects.all().order_by('-criado_em')
    serializer_class = AgendamentoSerializer

    def perform_create(self, serializer):
        agendamento = serializer.save()
        enviar_notificacao_email(agendamento)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        agendamento = Agendamento(**serializer.validated_data)

        try:
            agendamento.clean()  # Validações de horários e sobreposição
        except ValidationError as e:
            return Response({'detail': str(e)}, status=status.HTTP_400_BAD_REQUEST)

        self.perform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

def enviar_notificacao_email(agendamento):
    assunto = f'Novo Agendamento: {agendamento.nome}'
    mensagem = f'''
    Novo agendamento recebido.

    Nome: {agendamento.nome}
    Tipo: {agendamento.tipo}
    Data: {agendamento.data}
    Hora: {agendamento.hora}
    Email: {agendamento.email}
    Contato: {agendamento.contato}
    Nota: {agendamento.nota if agendamento.nota else 'N/A'}
    '''
    destinatario = settings.BACKOFFICE_EMAIL
    send_mail(assunto, mensagem, settings.DEFAULT_FROM_EMAIL, [destinatario])

@login_required
@user_passes_test(check_is_staff)
def gerenciamento_contactos_view(request):
    return render(request, 'backoffice/contactos/gerirContactos.html')

@login_required
@user_passes_test(check_is_staff)
def contactos_api_view(request):
    contactos = Contacto.objects.all().values('id', 'nome', 'email', 'mensagem', 'data_contacto', 'estado', 'validado_por', 'data_acao')
    return JsonResponse(list(contactos), safe=False)

@csrf_exempt
@login_required
@user_passes_test(check_is_staff)
def validar_contacto_view(request, contacto_id):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            contacto = Contacto.objects.get(id=contacto_id)
            contacto.estado = data.get('estado', contacto.estado)
            contacto.validado_por = data.get('validado_por', contacto.validado_por)
            contacto.data_acao = timezone.now() if contacto.estado else None
            contacto.save()
            return JsonResponse({'success': True})
        except Contacto.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Contacto não encontrado'})
    return JsonResponse({'success': False, 'error': 'Método não permitido'})

backoffice/templates/backoffice/admin/gerirAcessos.html
{% extends 'backoffice/baseBackoffice/base.html' %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block extra_css_backoffice %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Gerir Funcionários</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'backoffice/css/admin/home.css' %}">
    <script src="{% static 'backoffice/javaScript/admin/home.js' %}"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <style>
        article, aside, figcaption, figure, header, hgroup, nav, section {
            display: flex !important;
        }

        a:hover {
            text-decoration: none;
        !important;
        }

        body {
            font-family: "Prompt", sans-serif;
            color: #0f0f0f;
        }

    </style>
{% endblock %}

{% block content-backoffice %}
    <body>
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2>Gerir <b>Funcionários</b></h2>
                        </div>
                        <div class="col-sm-6">
                            <a href="{% url 'backoffice:user_create' %}" class="btn btn-success"><i
                                    class="material-icons">&#xE147;</i>
                                <span>Adicionar Novo Funcionário</span></a>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-sm-4">
                            <input type="text" id="filter-nome" class="form-control"
                                   placeholder="Pesquisar por Nome...">
                        </div>
                        <div class="col-sm-4">
                            <input type="text" id="filter-email" class="form-control"
                                   placeholder="Pesquisar por Email...">
                        </div>
                        <div class="col-sm-4">
                            <button id="clear-filters" class="btn btn-secondary">Limpar Filtros</button>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover mt-3">
                    <thead>
                    <tr>
                        <th>
                        <span class="custom-checkbox">
                            <input type="checkbox" id="selectAll">
                            <label for="selectAll"></label>
                        </span>
                        </th>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Palavra-Passe</th>
                        <th>Data de Criação</th>
                        <th>Usuário que Criou</th>
                        <th>Última Data de Alteração</th>
                        <th>Usuário que Alterou</th>
                        <th>Ações</th>
                    </tr>
                    </thead>
                    <tbody id="users-list">
                    {% for user in users %}
                        <tr>
                            <td>
                            <span class="custom-checkbox">
                                <input type="checkbox" id="checkbox{{ forloop.counter }}" name="options[]"
                                       value="{{ user.id }}">
                                <label for="checkbox{{ forloop.counter }}"></label>
                            </span>
                            </td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.email }}</td>
                            <td>
                                <input type="password" value="{{ user.password }}" class="form-control password-field"
                                       readonly>
                                <button class="btn btn-link toggle-password" data-password="{{ user.password }}">
                                    Mostrar
                                </button>
                            </td>
                            <td>{{ user.date_joined }}</td>
                            <td>{{ user.created_by }}</td>
                            <td>{{ user.last_modified }}</td>
                            <td>{{ user.modified_by }}</td>
                            <td>
                                <a href="#" class="edit" data-id="{{ user.id }}" data-toggle="modal"
                                   data-target="#editEmployeeModal"><i class="material-icons" data-toggle="tooltip"
                                                                       title="Edit">&#xE254;</i></a>
                                <a href="#" class="delete" data-id="{{ user.id }}" data-toggle="modal"
                                   data-target="#deleteEmployeeModal"><i class="material-icons" data-toggle="tooltip"
                                                                         title="Delete"> &#xE872; </i></a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="9" class="text-center">Nenhum usuário encontrado.</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="clearfix">
                    <div class="hint-text">Mostrando <b>{{ users|length }}</b> usuários</div>
                    <ul class="pagination">
                        <!-- Implementar paginação se necessário -->
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- templates/backoffice/admin/home.html -->

    <div class="container-xl">
        <!-- Sua tabela e outros elementos aqui -->
        <div id="modalContainer"></div> <!-- Contêiner para carregar modais -->
    </div>
    <script src="{% static 'backoffice/javaScript/admin/home.js' %}"></script>
    </body>
{% endblock %}
</html>

backoffice/templates/backoffice/admin/userCreate.html
<!-- templates/backoffice/admin/userCreate.html -->
{% load static %}
<!DOCTYPE html>
{% block extra_css_backoffice %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Criar Usuário</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'backoffice/css/admin/home.css' %}">
{% endblock %}

{% block content-backoffice %}
<body>
<div id="addEmployeeModal" class="modal fade show">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="createForm" method="post" action="{% url 'backoffice:user_create' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h4 class="modal-title">Adicionar Funcionário</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    {{ form.as_p }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Adicionar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="{% static 'backoffice/javaScript/admin/home.js' %}"></script>
</body>
{% endblock %}

backoffice/templates/backoffice/admin/userDelete.html
<!-- templates/backoffice/admin/userDeleteConfirm.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sua Página</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'backoffice/css/admin/home.css' %}">
    <script src="{% static 'backoffice/javaScript/admin/home.js' %}"></script>
</head>

<body>
  <!-- templates/backoffice/admin/userDelete.html -->
<div id="deleteEmployeeModal" class="modal fade show">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="deleteForm" method="post" action="{% url 'backoffice:user_delete' user.id %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h4 class="modal-title">Apagar Funcionário</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Tem certeza que deseja apagar {{ user.username }}?</p>
                    <p class="text-warning"><small>Esta ação não pode ser desfeita.</small></p>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
                    <input type="submit" class="btn btn-danger" value="Apagar">
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

backoffice/templates/backoffice/admin/userEdit.html
{% extends 'backoffice/baseBackoffice/base.html' %}

{% load static %}
<!DOCTYPE html>
<html lang="en">

    {% block extra_css_backoffice %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Editar Usuário</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'backoffice/css/admin/home.css' %}">
    <script src="{% static 'backoffice/javaScript/admin/home.js' %}"></script>
    {% endblock %}

{% block content-backoffice %}
<body>
    <div id="editEmployeeModal" class="modal fade show">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="editForm" method="post" action="{% url 'backoffice:user_edit' user.id %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h4 class="modal-title">Editar Funcionário</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="id_username">Nome</label>
                        <input type="text" class="form-control" id="id_username" name="username" value="{{ user.username }}" required>
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        <input type="email" class="form-control" id="id_email" name="email" value="{{ user.email }}" required>
                    </div>
                    <div class="form-group">
                        <label for="id_phone">Telefone</label>
                        <input type="text" class="form-control" id="id_phone" name="phone" value="{{ user.phone|default:'' }}">
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
                    <input type="submit" class="btn btn-info" value="Salvar">
                </div>
            </form>
        </div>
    </div>
</div>
</body>
{% endblock %}