Cliente/urls.py
# ptclinic/cliente/urls.py
from django.urls import path
from . import views
from .views import cadastro_view, contacto_view

urlpatterns = [
    path('', views.LadingPage, name='cliente_base'),
    path('cliente/agendar', views.Agendamento, name='agendar'),
    path('cadastro/', cadastro_view, name='cadastro'),  # URL de cadastro
    path('contacto/', contacto_view, name='contacto'),  # URL de contato
]

PTCLINIC/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cliente.urls')),
    path('', include('backoffice.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backoffice/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from . import views
from .views import AgendamentoViewSet, gerenciamento_cadastros_view, cadastros_api_view, contactos_api_view, \
    gerenciamento_contactos_view, user_list_api, atualizar_estado_cadastro

app_name = 'backoffice'
router = DefaultRouter()
router.register(r'agendamentos', AgendamentoViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('login/', views.Login, name='login'),  # Login do backoffice
    path('gerir-agendamentos/', TemplateView.as_view(template_name="backoffice/agendamentos/gerirAgendamentos.html"),
         name='gerir-agendamentos'),
    path('backoffice/', views.LadingPage, name='landingPage'),  # Criar novo usuário
    path('home/', views.LadingPage, name='home_backoffice'),
    path('gerir-cadastros/', gerenciamento_cadastros_view, name='gerenciamento_cadastros'),
    path('api/cadastros/', cadastros_api_view, name='cadastros_api'),  # Certifique-se de que esta URL está correta
    path('api/cadastros/<int:id>/atualizar-estado/', atualizar_estado_cadastro, name='atualizar_estado_cadastro'),

    path('api/contactos/', contactos_api_view, name='contactos_api'),
    path('gerir-contactos/', gerenciamento_contactos_view, name='gerenciamento_contactos'),
    path('api/contactos/<int:contacto_id>/validar/', views.validar_contacto_view, name='validar_contacto'),

    path('users/new/', views.user_create, name='user_create'),  # Criar novo usuário
    path('users/<int:user_id>/edit/', views.user_edit, name='user_edit'),
    path('users/<int:user_id>/delete/', views.user_delete, name='user_delete'),
    path('gerir-acessos/', views.Gerir_Acessos, name='Gerir_Acessos'),  # Dashboard do backoffice
    path('api/users/', user_list_api, name='user_list_api'),  # API de listagem de usuários
    # Adicione outras URLs conforme necessário
]

backoffice/models.py
from datetime import time, timedelta, datetime, date

from django.contrib.auth.models import User
from django.db import models
from rest_framework.exceptions import ValidationError

# models.py
from django.db import models

class Cadastro(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField()
    telemovel = models.CharField(max_length=20)
    data_cadastro = models.DateTimeField(auto_now_add=True)
    estado = models.BooleanField(default=False)
    usuario_acao = models.CharField(max_length=100, null=True, blank=True)
    data_acao = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.nome

class Agendamento(models.Model):
    TIPO_CHOICES = [
        ('Consulta', 'Consulta'),
        ('Visita', 'Visita'),
        ('Avaliação Física', 'Avaliação Física'),
    ]

    nome = models.CharField(max_length=100)
    tipo = models.CharField(max_length=50, choices=TIPO_CHOICES)
    data = models.DateField()
    hora = models.TimeField()
    email = models.EmailField()
    contato = models.CharField(max_length=20)
    nota = models.TextField(blank=True, null=True)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.nome} - {self.tipo} em {self.data} às {self.hora}'

    def clean(self):
        # Verificar horário de funcionamento
        if self.data.weekday() == 6:  # Domingo
            raise ValidationError('O ginásio está fechado aos domingos.')

        hora_abertura, hora_fechamento = self.get_horarios_funcionamento()

        if not (hora_abertura <= self.hora <= hora_fechamento):
            raise ValidationError(
                f'Horário de agendamento inválido. O ginásio abre às {hora_abertura} e fecha às {hora_fechamento}.')

        # Verificar sobreposição
        duracao = self.get_duracao()
        hora_fim = (datetime.combine(date.today(), self.hora) + duracao).time()

        agendamentos_conflitantes = Agendamento.objects.filter(
            data=self.data,
            hora__lt=hora_fim,
            hora__gte=self.hora
        ).exclude(pk=self.pk)

        if agendamentos_conflitantes.exists():
            raise ValidationError('Já existe um agendamento neste horário.')

    def get_horarios_funcionamento(self):
        if self.data.weekday() in [0, 1, 2, 3, 4]:  # Segunda a sexta
            return time(7, 0), time(21, 30)
        elif self.data.weekday() == 5:  # Sábado
            return time(9, 0), time(13, 0)
        return None, None

    def get_duracao(self):
        if self.tipo == 'Consulta':
            return timedelta(hours=1)
        elif self.tipo == 'Visita':
            return timedelta(minutes=30)
        elif self.tipo == 'Avaliação Física':
            return timedelta(minutes=45)
        return timedelta(0)

    def save(self, *args, **kwargs):
        self.clean()  # Chamar validação antes de salvar
        super().save(*args, **kwargs)


class Contacto(models.Model):
    nome = models.CharField(max_length=255)
    email = models.EmailField()
    mensagem = models.TextField()
    data_contacto = models.DateTimeField(auto_now_add=True)
    estado = models.BooleanField(default=False)
    validado_por = models.CharField(max_length=255, null=True, blank=True)
    data_acao = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.nome

backoffice/forms.py
# forms.py

from django import forms
from django.contrib.auth.models import User

from backoffice.models import Cadastro
from cliente.models import CadastroImage


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Senha")
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Confirme a senha")

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if self.instance.pk is None and User.objects.filter(username=username).exists():
            raise forms.ValidationError("Nome de usuário já está em uso.")
        return username

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("As senhas não coincidem.")

        return cleaned_data

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']  # Inclua outros campos que você deseja permitir que sejam editados

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        # Customize os campos se necessário
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class CadastroForm(forms.ModelForm):
    class Meta:
        model = Cadastro
        fields = ['nome', 'email', 'telemovel']

backoffice/views.py
import json
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from rest_framework import viewsets, status
from rest_framework.exceptions import ValidationError
from rest_framework.response import Response

from backoffice.forms import UserCreationForm, UserEditForm
from backoffice.models import Agendamento, Cadastro, Contacto
from backoffice.serializers import AgendamentoSerializer
from cliente.models import CadastroImage

def check_is_staff(user):
    return user.is_staff
@login_required
@user_passes_test(check_is_staff)
def LadingPage(request):
    return render(request, 'backoffice/landingPage/landingPage.html')

@login_required
@user_passes_test(check_is_staff)
def gerenciamento_cadastros_view(request):
    return render(request, 'backoffice/cadastro/gerirCadastros.html')

@login_required
@user_passes_test(check_is_staff)
def cadastros_api_view(request):
    cadastros = Cadastro.objects.all().values('id', 'nome', 'email', 'telemovel', 'data_cadastro', 'estado', 'usuario_acao', 'data_acao')
    return JsonResponse(list(cadastros), safe=False)

@csrf_exempt
@login_required
@user_passes_test(check_is_staff)
def atualizar_estado_cadastro(request, id):
    if request.method == 'POST':
        try:
            cadastro = Cadastro.objects.get(id=id)
            data = json.loads(request.body)
            cadastro.estado = data['estado']
            cadastro.usuario_acao = data['usuario_acao']
            cadastro.data_acao = data['data_acao']
            cadastro.save()
            return JsonResponse({'success': True})
        except Cadastro.DoesNotExist:
            return HttpResponseBadRequest('Cadastro não encontrado')
        except Exception as e:
            return HttpResponseBadRequest(f'Erro: {str(e)}')
    else:
        return HttpResponseBadRequest('Método não permitido')

def Login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active and user.is_staff:
                    login(request, user)
                    return redirect(reverse('backoffice:landingPage'))
                else:
                    messages.error(request, 'A conta não tem permissões para acessar essa área.')
            else:
                messages.error(request, 'Nome de usuário ou senha inválidos.')
        else:
            messages.error(request, 'Nome de usuário ou senha inválidos.')
    else:
        form = AuthenticationForm()
    return render(request, 'backoffice/login/login.html', {'form': form})

@login_required
@user_passes_test(check_is_staff)
def user_list_api(request):
    if request.method == 'GET':
        users = User.objects.filter(is_staff=True).values('id', 'username', 'email', 'date_joined')
        users_list = list(users)
        return JsonResponse(users_list, safe=False)

@login_required
@user_passes_test(check_is_staff)
def Gerir_Acessos(request):
    users = User.objects.filter(is_staff=True)  # Filtra apenas usuários que são staff
    return render(request, 'backoffice/admin/gerirAcessos.html', {'users': users})

@login_required
@user_passes_test(check_is_staff)
def user_create(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Novo usuário adicionado com sucesso!')
            return redirect('backoffice:home_backoffice')
    else:
        form = UserCreationForm()
    return render(request, 'backoffice/admin/userCreate.html', {'form': form})

@login_required
@user_passes_test(check_is_staff)
def user_edit(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário atualizado com sucesso!')
            return redirect('backoffice:home_backoffice')
    else:
        form = UserEditForm(instance=user)
    return render(request, 'backoffice/admin/userEdit.html', {'user': user, 'form': form})

@login_required
@user_passes_test(check_is_staff)
def user_delete(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        user.delete()
        messages.success(request, 'Usuário apagado com sucesso!')
        return redirect('backoffice:home_backoffice')
    return render(request, 'backoffice/admin/userDelete.html', {'user': user})

class AgendamentoViewSet(viewsets.ModelViewSet):
    queryset = Agendamento.objects.all().order_by('-criado_em')
    serializer_class = AgendamentoSerializer

    def perform_create(self, serializer):
        agendamento = serializer.save()
        enviar_notificacao_email(agendamento)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        agendamento = Agendamento(**serializer.validated_data)

        try:
            agendamento.clean()  # Validações de horários e sobreposição
        except ValidationError as e:
            return Response({'detail': str(e)}, status=status.HTTP_400_BAD_REQUEST)

        self.perform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

def enviar_notificacao_email(agendamento):
    assunto = f'Novo Agendamento: {agendamento.nome}'
    mensagem = f'''
    Novo agendamento recebido.

    Nome: {agendamento.nome}
    Tipo: {agendamento.tipo}
    Data: {agendamento.data}
    Hora: {agendamento.hora}
    Email: {agendamento.email}
    Contato: {agendamento.contato}
    Nota: {agendamento.nota if agendamento.nota else 'N/A'}
    '''
    destinatario = settings.BACKOFFICE_EMAIL
    send_mail(assunto, mensagem, settings.DEFAULT_FROM_EMAIL, [destinatario])

@login_required
@user_passes_test(check_is_staff)
def gerenciamento_contactos_view(request):
    return render(request, 'backoffice/contactos/gerirContactos.html')

@login_required
@user_passes_test(check_is_staff)
def contactos_api_view(request):
    contactos = Contacto.objects.all().values('id', 'nome', 'email', 'mensagem', 'data_contacto', 'estado', 'validado_por', 'data_acao')
    return JsonResponse(list(contactos), safe=False)

@csrf_exempt
@login_required
@user_passes_test(check_is_staff)
def validar_contacto_view(request, contacto_id):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            contacto = Contacto.objects.get(id=contacto_id)
            contacto.estado = data.get('estado', contacto.estado)
            contacto.validado_por = data.get('validado_por', contacto.validado_por)
            contacto.data_acao = timezone.now() if contacto.estado else None
            contacto.save()
            return JsonResponse({'success': True})
        except Contacto.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Contacto não encontrado'})
    return JsonResponse({'success': False, 'error': 'Método não permitido'})

backoffice/templates/backoffice/baseBackoffice/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PT Clinic</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'backoffice/css/base/base.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Prompt:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="icon" href="{% static 'cliente/images/iconPTCLINIC/icon-PtClinic.jpg' %}">

    {% block extra_css_backoffice %}

    {% endblock %}

</head>
<body>
<header>
    <nav>
        <div class="logo-ptclinic">
            <a href=""><img width="185px" height="185px" src="{% static 'cliente/images/iconPTCLINIC/PT x.jpg' %}"
                            alt=""></a>
        </div>

        <div class="right">
            <a href="{% url 'backoffice:landingPage' %}">Home</a>
            <a href="/#cadastro">Editar Cadastro</a>
            <a href="/#map-class">Editar Mapa de Aulas</a>

            <div class="services">
                Administrativa <i class="fa-solid fa-chevron-down"></i>
                <ul class="services-dropdown">
                    <li><a href="{% url 'backoffice:Gerir_Acessos' %}">Gerir Acessos</a></li>
                    <li><a href="{% url 'backoffice:gerenciamento_contactos' %}">Gerir Contactos</a></li>
                    <li><a href="{% url 'backoffice:gerenciamento_cadastros' %}">Gerir Cadastros</a></li>
                    <li class="has-submenu">
                        <a href="#">Gerir Publicações e Anúncios</a>
                        <ul class="submenu">
                            <li><a href="https://pt-pt.facebook.com/login.php/">Facebook</a></li>
                            <li><a href="https://www.instagram.com/accounts/login/">Instagram</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <button class="button" onclick="window.location.href='{% url 'backoffice:gerir-agendamentos' %}'">Gerir
                Agenda
            </button>
            <button class="button" onclick="window.location.href='{% url 'backoffice:login' %}'">Sair</button>
        </div>

    </nav>
</header>

<main>
    {% block content-backoffice %}

    {% endblock %}
</main>

<footer>
    <div class="footer-apoio">
        <h2>Acordos</h2>
        <p>Temos acordos com todas a companhias
            de seguros e sistemas de saúde</p>

        <div class="logo-1">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-MinisterioSaude@4x.png' %}"
                 alt="">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-AdvanceCare@4x.png' %}" alt="">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-ACP@4x.png' %}" alt="">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-FutureHealthCare@4x.png' %}"
                 alt="">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-Allianz@4x.png' %}" alt="">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-SaudePrime@4x.png' %}" alt="">
        </div>
        <div class="logo-2">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-Medis@4x.png' %}" alt="">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-Medicare@4x.png' %}" alt="">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-Multicare@4x.png' %}" alt="">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-JoaquimChavesSaude@4x.png' %}"
                 alt="">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-SynLab@4x.png' %}" alt="">
            <img width="100px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-SAMS@4x.png' %}" alt="">
        </div>
        <div class="line"></div>
        <h4>Empresa protegida contra dívidas pela</h4>
        <img width="150px" src="{% static 'cliente/images/logosfooter/LOGO-FOOTER-Intrum@4x.png' %}" alt="">

    </div>

    <div class="footer-info">
        <img width="20%" src="{% static 'cliente/images/logosfooter/logo-assinatura.png' %}" alt="">
        <p class="white-color">
            Centro Comercial Colina do Sol - Loja 27
            <br>
            Praceta Manuela Porto, Nº1 - 2650-191 Encosta do Sol
        </p>
        <p class="white-color">211 555 983 | 932 180 800 | geral@ptclinic.pt
        <p>siga-nos</p>
        <div class="icon-social">
            <img width="50px" height="50px" src="{% static 'cliente/images/iconsRedesSocial/google.png' %}" alt="">
            <img width="50px" height="50px" src="{% static 'cliente/images/iconsRedesSocial/gps.png' %}" alt="">
            <img width="50px" height="50px" src="{% static 'cliente/images/iconsRedesSocial/facebook.png' %}" alt="">
            <img width="50px" height="50px" src="{% static 'cliente/images/iconsRedesSocial/instagram.png' %}" alt="">
        </div>
        <div class="reserved-policy">
            PT Clinic ©2023 | Todos os direitos reservados |
            <span><a class="policy" href="">Política de Privacidade</a></span>
        </div>
    </div>
</footer>
</body>
</html>